using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WeText.Common.Querying;

namespace WeText.Services.Texting.Model
{
    [ToTable("Texts")]
    public class TextTableObject
    {
        [Key(AutoGenerated = false)]
        public string Id { get; set; }

        public string UserId { get; set; }


        public string Title { get; set; }

        public string Content { get; set; }

        public DateTime DateCreated { get; set; }
    }
}
