using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace WeText.Common.Querying
{
    [AttributeUsage(AttributeTargets.Property, AllowMultiple = false, Inherited = true)]
    public class KeyAttribute : Attribute
    {
        public bool AutoGenerated { get; set; }

        public KeyAttribute(bool autoGenerated = true)
        {
            this.AutoGenerated = autoGenerated;
        }
    }
}
